
name: Build

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install dependecies
        run: npm install
      - name: Create environment file
        run: |
          touch .env.production.local
          echo REACT_APP_API_KEY=123456789 >> .env.production.local
          echo REACT_APP_AUTH_DOMAIN=123456789 >> .env.production.local
          echo REACT_APP_DATABASE_URL=123456789 >> .env.production.local
          echo REACT_APP_PROJECT_ID=123456789 >> .env.production.local
          echo REACT_APP_STORAGE_BUCKET=123456789 >> .env.production.local
          echo REACT_APP_MESSAGING_SENDER_ID=123456789 >> .env.production.local
          echo REACT_APP_APP_ID=123456789 >> .env.production.local
          echo REACT_APP_MEASUREMENT_ID=123456789 >> .env.production.local
      - name: Build
        run: npm run build
